default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
witches-town: styles/witches-town.scss
# black-cat: styles/black-cat.scss
# cafe: styles/cafe.scss