name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
    
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
          repository: melocery/mastodon
          tags: v3.5.1
